version: '2'
services:
  cowcheck:
    image: ${ecr_repos_account}.dkr.ecr.${aws_region}.amazonaws.com/cowcheck:latest
    stdin_open: true
    dns_search:
    - healthcheck.rancher.internal
    - healthcheck.healthcheck.rancher.internal
    - rancher.internal
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    dns:
    - 169.254.169.250
    tty: true
    ports:
    - ${host_port}:5050/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
