wekandb1:
  image: mongo
#  volumes:
#    - ./data/runtime/db:/data/db
#    - ./data/dump:/dump
  command: mongod --smallfiles --oplogSize 128
  ports:
    - 27017

wekan1:
  image: mquandalle/wekan
  links:
    - wekandb1
  environment:
    - MONGO_URL=mongodb://wekandb1/wekan1
    - ROOT_URL=http://localhost:80
  ports:
    - 80:80
