.catalog:
  name: cowcheck
  version: v0.1
  description: "HTTP Health end point of a Rancher Worker"
  minimum_rancher_version: v1.5.0
  questions:
    - variable: public_port
      description: "public port to access the wordpress site"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"
    - variable: aws_region
      description: "AWS Region that hosts the ECR"
      label: "AWS Region"
      required: true
      default: "ap-southeast-2"
      type: "string"
    - variable: ecr_repos_account
      description: "Account where ECR is hosted"
      label: "ECR Repos Account"
      required: true
      type: "string"
    - variable: container_to_monitor
	  description: "Container which needs to be monitored"
      label: "Container to monitor"
      default: "logspout"
      required: true
      type: "string"

cowcheck:
  scale: 1