name: Cowcheck
description: "HTTP Health end point of a Rancher Worker"
version: latest
category: Management
maintainer: "TOP Engineering <DMPS-TOP@team.telstra.com>"
support: "Maintained by Telstra AMP/TOP Team"
license: 
projectURL: 